language: node_js

cache:
  npm: true

env:
  global:
    - MNEMONIC="myth like bonus scare over problem client lizard pioneer submit female collect"

before_install:
  - npm install -g truffle

script:
  - npm run coverage
  - npm run coveralls

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
