language: node_js

cache:
  npm: true

env:
  global:
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"

script:
  - npm run coverage
  - npm run coveralls

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
