language: node_js

cache:
  npm: true

env:
  global:
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"

before_install:
  - npm install -g truffle coveralls
  - ganache-cli -m "$MNEMONIC" --port 9545 --networkId 4447 -g 10000000000 &

script:
  - npm run coverage
  - npm run coveralls

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
